version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_blog_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]

volumes:
  postgres_data:
